export const products = [
  {
    slug: "acrylic-clocks",
    category: "all-products",
    title: "Modern Wall Clock",
    description: "Stylish and silent wall clock for home and office decor.",
    price: 499,
    image: "/clock.png",
    stock: true,
  },
  {
    slug: "tshirts",
    category: "all-products",
    title: "Custom Printed T-Shirt",
    description: "Premium cotton T-shirt with customizable design and print.",
    price: 599,
    image: "/printed-tshirt.png",
    stock: true,
  },
  {
    slug: "tumbler",
    category: "all-products",
    title: " Personalized Pink And Purple Tumbler", 
    description: "Stylish tumbler with a personalized touch.",
    price: 299,
    image: "/sipper.png",
    stock: true,
  
  },
  {
    slug: "notebooks",
    category: "office-stationeries-notebooks",
    title: "Personalized Notebook",
    description: "Customizable notebook with your name or logo.",
    price: 299,
    image: "/dairy.png",
    stock: true,
  },
  {
    slug: "custom-posters",
    category: "office-stationeries-notebooks",
    title: "Custom Posters",
    description: "High-quality posters with your design or artwork.",
    price: 249,
    image: "/posters.png",
    stock: false,
  },
  {
    slug: "Pens",
    category: "office-stationeries-notebooks",
    title: "Custom Pens",
    description: "Stylish pens with your logo or design.",
    price: 49,
    image: "/penn.png",
    stock: true,
  },
  {
    slug: "bags",
    category: "all-products",
    title: "Bag",
    description: "Durable and eco-conscious bag ideal for everyday use.",
    price: 349,
    image: "/bag.png",
    stock: true,
  },
  {
    slug: "medals",
    category: "all-products",
    title: "Custom Acrylic Medal",
    description: "Personalized acrylic medal for events and achievements.",
    price: 240,
    image: "/medal.png",
    stock: true,
  },
  {
    slug: "baggy-hats",
    category: "all-products",
    title: "Baggy Hat",
    description: "Stylish and comfortable baggy hat for all occasions.",
    price: 299,
    image: "/baggy-hats.png",
    stock: false,
  },

  // Drinkware

    {
    slug: "pink-tumbler",
    category: "drinkware",
    title: " Personalized Pink And Purple Tumbler", 
    description: "Stylish tumbler with a personalized touch.",
    price: 299,
    image: "/sipper.png",
    stock: true,
  
  },

  {
    slug: "mugs",
    category: "drinkware",
    title: "Custom Mug",
    description: "Personalized ceramic mug with your photo or logo.",
    price: 179,
    image: "/mug.png",
    stock: true,
  },
  {
    slug: "water-bottles",
    category: "drinkware",
    title: "Stainless Steel Water Bottle",
    description: "Insulated bottle to keep your drinks hot or cold.",
    price: 349,
    image: "/bottle2.png",
    stock: true,
  },
  {
    slug: "black-coffee-mugs",
    category: "drinkware",
    title: "Black Coffee Mug",
    description: "Elegant black coffee mug with customizable design.",
    price: 199,
    image: "/magic-mug.png",
    stock: false,
  },
  {
    slug: "insulated-bottle-drinkware",
    category: "drinkware",
    title: "Insulated Water Bottle",
    description: "Keeps your drinks cold or hot for hours. BPA-free and stylish.",
    price: 399,
    image: "/bottle.png",
    stock: true,
  },

  // T-Shirts, Caps & Bags
  {
    slug: "custom-tshirts",
    category: "t-shirts-caps-bags",
    title: "Custom T-Shirt",
    description: "Premium cotton T-shirt with your own print.",
    price: 599,
    image: "/tshirt.png",
    stock: true,
  },
    {
    slug: "bag",
    category: "t-shirts-caps-bags",
    title: "Bag",
    description: "Durable and eco-conscious bag ideal for everyday use.",
    price: 349,
    image: "/bag.png",
    stock: true,
  },

  {
    slug: "polo-tshirts",
    category: "t-shirts-caps-bags",
    title: "Polo T-Shirt",
    description: "Classic polo T-shirt for a smart casual look.",
    price: 699,
    image: "/polo.png",
    stock: true,
  },
  {
    slug: "caps",
    category: "t-shirts-caps-bags",
    title: "Custom Cap",
    description: "Personalized cap with embroidered logo or text.",
    price: 249,
    image: "/cap.png",
    stock: true,
  },
  {
    slug: "bags-tcb",
    category: "t-shirts-caps-bags",
    title: "Trendy Bag",
    description: "Trendy and durable bag for everyday use.",
    price: 399,
    image: "/bagg.png",
    stock: true,
  },

  // Photo Frames & Gifts
  {
    slug: "wooden-frames",
    category: "photo-frames-gifts",
    title: "Wooden Photo Frame",
    description: "Elegant wooden frame for your cherished memories.",
    price: 349,
    image: "/wooden.png",
    stock: true,
  },
  {
    slug: "Customize-Keychain",
    category: "photo-frames-gifts",
    title: "Customize-Keychain",
    description: "Personalized keychain with your name or photo.",
    price: 199,
    image: "/key.png",

    stock: true,
  },
  {
    slug: "photo-gifts",
    category: "photo-frames-gifts",
    title: "Photo Gift",
    description: "Custom photo gifts for every occasion.",
    price: 299,
    image: "/frame.png",
    stock: true,
  },
  {
    slug: "family-photo-puzzle",
    category: "photo-frames-gifts",
    title: "Family Photo Puzzle",
    description: "Fun and unique puzzle made from your family photo.",
    price: 399,
    image: "/puzzel.png",
    stock: false,
  },
];
